list_stock:
    path: /
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\ListGarmentSizeController::__invoke
    methods: [GET]

create_garmentsize:
    path: /newgarmentsize
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\GarmentSizeTableController:__invoke
    methods: [POST]

update_garmentsize:
    path: /updategarmentsize
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\UpdateGarmentSizeController:__invoke
    methods: [POST]