list_stock:
    path: /list
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\ListGarmentSizeController::__invoke
    methods: [PUT]

create_garmentsize:
    path: /create
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\GarmentSizeFillTableController:__invoke
    methods: [PUT]

update_garmentsize:
    path: /update
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\UpdateGarmentSizeController:__invoke
    methods: [PUT]
