insert_size:
    path: /create
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\Size\InsertNewSizeController::__invoke
    methods: [PUT]

update_size:
    path: /update
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\Size\UpdateSizeController::__invoke
    methods: [PUT]

list_sizes:
    path: /list
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\Size\ListAllSizeController::__invoke
    methods: [PUT]

list_sizes_by_garmentType:
    path: /listbygarmenttype
    controller: Inventory\Management\Infrastructure\Controller\GarmentSize\Size\ListSizeByGarmentTypeController::__invoke
    methods: [PUT]
