insert_size:
    path: /new
    controller: Inventory\Management\Infrastructure\Controller\ControllerSize::insertNewSize
    methods: [POST]

update_size:
    path: /update
    controller: Inventory\Management\Infrastructure\Controller\ControllerSize::updateSize
    methods: [POST]

list_sizes:
    path: /
    controller: Inventory\Management\Infrastructure\Controller\ControllerSize::listAllSize
    methods: [GET]

list_sizes_by_garmentType:
    path: /garmentType
    controller: Inventory\Management\Infrastructure\Controller\ControllerSize::listSizeByGarmentType
    methods: [POST]