admin_department:
    resource: ./routes/admin/department/department.yaml
    prefix: /admin/department

admin_employee:
    resource: ./routes/admin/employee/employee.yaml
    prefix: /admin/employee

user_employee:
    resource: ./routes/user/employee/employee.yaml
    prefix: /employee
