#index:
#    path: /
#    controller: App\Controller\DefaultController::index

SizeRoutes:
    resource: 'routes/SizeRoutes/size_routes.yaml'
    prefix: /size

GarmentRoutes:
    resource: 'routes/GarmentRoutes/garment_routes.yaml'
    prefix: /garment

Stock:
    resource: 'routes/GarmentSize/garment_size_routes.yaml'
    prefix: /stock