login_employee:
    path: /login

search_employee_user:
    path: /{nif}
    controller: Inventory\Management\Infrastructure\Controller\Employee\ShowEmployeeByNifController::showEmployeeByNif

update_basic_employee:
    path: /{nif}/update
    controller: Inventory\Management\Infrastructure\Controller\Employee\UpdateBasicFieldsEmployeeController::updateBasicFieldsEmployee
