create_department:
    path: /create
    controller: Inventory\Management\Infrastructure\Controller\Department\CreateDepartmentController::__invoke
    methods: [PUT]

create_subdepartment:
    path: /{department}/subdepartment/create
    controller: Inventory\Management\Infrastructure\Controller\Department\CreateSubDepartmentController::__invoke
    methods: [PUT]

list_departments:
    path: /list
    controller: Inventory\Management\Infrastructure\Controller\Department\ShowDepartmentsController::__invoke
    methods: [PUT]

update_department:
    path: /{department}/update
    controller: Inventory\Management\Infrastructure\Controller\Department\UpdateNameDepartmentController::__invoke
    methods: [PUT]

update_subdepartment:
    path: /subdepartment/{subdepartment}/update
    controller: Inventory\Management\Infrastructure\Controller\Department\UpdateNameSubDepartmentController::__invoke
    methods: [PUT]
